table Measure
	lineageTag: c5022e32-6d15-4933-98dc-9d82dcb316db

	measure Sales: =
			
			SUM(factinternetsales[SalesAmount])
		lineageTag: 5ff2d643-3a92-4401-9e22-6ed38067e414

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Measure = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

